# This file contains values from Cookiecutter

default_context:
  project_name: "privacy-query-engine"
  project_description: "A Python SDK for differential privacy and de-identification in SQL queries"
  organization: "privacy-query-engine"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "curleaf"
  email: "qbt2587496@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
